---
app_name: "flask_seed"
logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s %(levelname)s %(message)s"

    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout

        error_file_handler:
            class: logging.StreamHandler
            level: ERROR
            formatter: simple
            stream: ext://sys.stderr

    loggers:
        urllib3:
            level: INFO

    root:
        level: DEBUG
        handlers:
            - console
            - error_file_handler
